sudo: required
language: generic
dist: trusty

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: SODIUM_VERSION=1.0.16 SWIFT_VERSION=swift-4.2-RELEASE
    - os: linux
      dist: trusty
      sudo: required
      env: SODIUM_VERSION=1.0.16 SWIFT_VERSION=swift-4.1-RELEASE
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10

install:
  # Install libsodium on MacOS via homebrew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl libsodium; fi

  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

before_script:
  - swift --version
  - swift package clean
  - swift package resolve
  - swift build

script:
  - swift test --verbose