sudo: required
language: generic
dist: trusty

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: SODIUM_VERSION=1.0.17 SWIFT_VERSION=5.0 SWIFT_LINUX=5.0
    - os: osx
      osx_image: xcode10.2
      env: SWIFT_OSX=5.0
  # Alamofire won't compile on Linux, allow it to fail even though every other test will pass
  allow_failures:
    - env: SODIUM_VERSION=1.0.17 SWIFT_VERSION=5.0 SWIFT_LINUX=5.0

addons:
  apt:
    packages:
      - wget
      - curl
      - ca-certificates
      - libicu-dev
      - libstdc++6
      - libcurl4-openssl-dev
      - libssl-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:ondrej/php -y;
      sudo apt-get update -q;
      sudo apt-get install libsodium-dev -y;
    fi

install:
  # Install libsodium on MacOS via homebrew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl libsodium; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi

before_script:
  - ls -laht
  - swift --version
  - swift package clean
  - swift package resolve
  - swift build

script:
  - swift test --verbose